version: "3.8"

services:
  train:
    image: train:latest
    build:
      context: .
      dockerfile: train/Dockerfile
    volumes:
      - ./data:/data
      - ./db:/app/db
      - ./mlflow_artifacts:/app/mlflow_artifacts
    depends_on:
      - mlflow_server
    environment:
      MLFLOW_TRACKING_URI: http://mlflow_server:2137

  mlflow_server:
    image: server:latest
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "2137:2137"
    volumes:
      - ./db:/db